version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/csgigs
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install client dependencies
          command: npm install --prefix client
      - run:
          name: Build client
          command: CI=false npm run build --prefix client
      - run:
          name: Install server dependencies
          command: npm install --prefix server
      - run:
          name: Copying client build files to server
          command: cp -R client/build/. server/public
      - persist_to_workspace:
         root: .
         paths: .

  deploy:
    machine:
      enabled: true
    working_directory: ~/csgigs
    steps:
      - checkout
      - attach_workspace:
          at: ~/csgigs
      - run:
          name: Run deploy script
          command: ./do_deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build