version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/csgigs
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true 
      - run: docker build . -t csgigs:latest
  deploy:
    docker: 
      - image: csgigs:latest
    steps:
      - run:
          name: Run deploy script
          command: sh ./do_deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build