version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/csgigs
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true 
      # Build the docker image after git push
      - run: docker build . -t csgigs:latest


